---
services:
  pihole:
    image: pihole/pihole:latest
    container_name: svc.pi-hole
    hostname: docker.pi-hole
    restart: unless-stopped
    ports:
      - "53:53/tcp" # DNS
      - "53:53/udp" # DNS
      - "67:67/udp" # DHCP
      - "18080:80"
      - "18443:443"
    networks:
      docker-homelan:
        ipv4_address: 192.168.8.2
#    dns:
#      - 192.168.8.1
    environment:
      TZ: ${PIHOLE_TZ}
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
    env_file: .env # use .env
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
      - SYS_TIME
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole-secure.rule=Host(`pihole.local.${DOMAIN}`)" #CNAME
      - "traefik.http.routers.pihole-secure.entrypoints=https"
      - "traefik.http.routers.pihole-secure.tls=true"
      - "traefik.http.routers.pihole-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"

networks:
  docker-homelan:
    external: true
