---
services:
  portainer:
    container_name: svc.portainer
    hostname: portainer.local-lab.site
    image: portainer/portainer-ce:lts
    restart: unless-stopped
    ports:
      - "9000:9000"
    networks:
      docker-homelan:
        ipv4_address: 192.168.8.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./etc-portainer:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.local.local-lab.sites`)" #CNAME
      - "traefik.http.services.portainer.loadbalancer.server.port=90000"
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.routers.portainer.middlewares=auth"
    # add Basic Auth middleware for securing your portainer dashboards behind Traefik.
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.portainer.rule=Host(`portainer.local.local-lab.sites`)" #CNAME
#      - "traefik.http.routers.portainer.entrypoints=websecure"
#      - "traefik.http.routers.portainer.tls.certresolver=cloudflare"
#      - "traefik.http.routers.portainer.middlewares=auth"
#      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
networks:
  docker-homelan:
    external: true
